export const EMERGENCY_CONTENT = {
  en: {
    call112: "Call 112",
    heading: "Emergency and Legal Aid Resources",
    intro: "If you need urgent help, contact these resources directly.",
    policeTitle: "Police Emergency",
    policeDesc: "National emergency helpline for police assistance.",
    womenTitle: "Women Helpline",
    womenDesc: "National helpline for women in distress.",
    domesticTitle: "Domestic Violence Helpline",
    domesticDesc: "National helpline for domestic violence support.",
    childTitle: "Child Helpline",
    childDesc: "National helpline for children in need of help.",
    nalsaTitle: "National Legal Services Authority (NALSA)",
    nalsaDesc: "Free legal aid and services for eligible citizens.",
    consumerTitle: "Consumer Helpline",
    consumerDesc: "National Consumer Helpline for consumer grievances.",
    cyberTitle: "Cyber Crime Helpline",
    cyberDesc: "National helpline to report cyber crimes and online fraud.",
    seniorTitle: "Senior Citizen Helpline",
    seniorDesc: "National helpline for elderly citizens needing assistance.",
    disclaimer: "These are general national helpline numbers. In an emergency, always contact local police or emergency services directly.",
  },

  hi: {
    call112: "112 पर कॉल करें",
    heading: "इमरजेंसी और कानूनी सहायता नंबर",
    intro: "अगर आपको तुरंत मदद चाहिए, तो सीधे इन नंबरों पर संपर्क करें।",
    policeTitle: "पुलिस आपातकालीन सेवा",
    policeDesc: "पुलिस की मदद के लिए राष्ट्रीय इमरजेंसी नंबर।",
    womenTitle: "महिला हेल्पलाइन",
    womenDesc: "संकट में फंसी महिलाओं के लिए राष्ट्रीय हेल्पलाइन।",
    domesticTitle: "घरेलू हिंसा हेल्पलाइन",
    domesticDesc: "घरेलू हिंसा से पीड़ित लोगों की मदद के लिए राष्ट्रीय हेल्पलाइन।",
    childTitle: "चाइल्ड हेल्पलाइन (बच्चों की मदद)",
    childDesc: "मदद की जरूरत वाले बच्चों के लिए राष्ट्रीय हेल्पलाइन।",
    nalsaTitle: "राष्ट्रीय कानूनी सेवा प्राधिकरण (NALSA)",
    nalsaDesc: "जरूरतमंद नागरिकों के लिए मुफ्त कानूनी मदद और सेवाएं।",
    consumerTitle: "ग्राहक हेल्पलाइन",
    consumerDesc: "खरीदे गए सामान या सेवा से जुड़ी शिकायतों के लिए राष्ट्रीय हेल्पलाइन।",
    cyberTitle: "साइबर क्राइम हेल्पलाइन",
    cyberDesc: "ऑनलाइन धोखाधड़ी और साइबर अपराध की रिपोर्ट करने के लिए हेल्पलाइन।",
    seniorTitle: "वरिष्ठ नागरिक हेल्पलाइन",
    seniorDesc: "बुजुर्ग नागरिकों की सहायता के लिए राष्ट्रीय हेल्पलाइन।",
    disclaimer: "ये सामान्य राष्ट्रीय हेल्पलाइन नंबर हैं। किसी भी आपात स्थिति में, हमेशा स्थानीय पुलिस या नजदीकी आपातकालीन सेवा से सीधे संपर्क करें।",
  },

  kn: {
    call112: "112 ಕ್ಕೆ ಕರೆ ಮಾಡಿ",
    heading: "ತುರ್ತು ಮತ್ತು ಕಾನೂನು ನೆರವಿನ ಸಂಖ್ಯೆಗಳು",
    intro: "ನಿಮಗೆ ತಕ್ಷಣದ ಸಹಾಯ ಬೇಕಾದರೆ, ಈ ಸಂಖ್ಯೆಗಳನ್ನು ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ.",
    policeTitle: "ಪೊಲೀಸ್ ತುರ್ತು ಸೇವೆ",
    policeDesc: "ಪೊಲೀಸ್ ನೆರವಿಗಾಗಿ ರಾಷ್ಟ್ರೀಯ ತುರ್ತು ಸಹಾಯವಾಣಿ.",
    womenTitle: "ಮಹಿಳಾ ಸಹಾಯವಾಣಿ",
    womenDesc: "ಸಂಕಷ್ಟದಲ್ಲಿರುವ ಮಹಿಳೆಯರಿಗಾಗಿ ರಾಷ್ಟ್ರೀಯ ಸಹಾಯವಾಣಿ.",
    domesticTitle: "ಕೌಟುಂಬಿಕ ದೌರ್ಜನ್ಯ ಸಹಾಯವಾಣಿ",
    domesticDesc: "ಕೌಟುಂಬಿಕ ದೌರ್ಜನ್ಯಕ್ಕೆ ಒಳಗಾದವರ ನೆರವಿಗಾಗಿ ರಾಷ್ಟ್ರೀಯ ಸಹಾಯವಾಣಿ.",
    childTitle: "ಮಕ್ಕಳ ಸಹಾಯವಾಣಿ",
    childDesc: "ನೆರವು ಬೇಕಾದ ಮಕ್ಕಳಿಗಾಗಿ ರಾಷ್ಟ್ರೀಯ ಸಹಾಯವಾಣಿ.",
    nalsaTitle: "ರಾಷ್ಟ್ರೀಯ ಕಾನೂನು ಸೇವೆಗಳ ಪ್ರಾಧಿಕಾರ (NALSA)",
    nalsaDesc: "ಅರ್ಹ ನಾಗರಿಕರಿಗೆ ಉಚಿತ ಕಾನೂನು ನೆರವು ಮತ್ತು ಸೇವೆಗಳು.",
    consumerTitle: "ಗ್ರಾಹಕ ಸಹಾಯವಾಣಿ",
    consumerDesc: "ಗ್ರಾಹಕ ಹಕ್ಕುಗಳು ಮತ್ತು ದೂರುಗಳಿಗಾಗಿ ರಾಷ್ಟ್ರೀಯ ಸಹಾಯವಾಣಿ.",
    cyberTitle: "ಸೈಬರ್ ಕ್ರೈಮ್ ಸಹಾಯವಾಣಿ",
    cyberDesc: "ಆನ್‌ಲೈನ್ ವಂಚನೆ ಮತ್ತು ಸೈಬರ್ ಅಪರಾಧ ದೂರುಗಳಿಗಾಗಿ ಸಹಾಯವಾಣಿ.",
    seniorTitle: "ಹಿರಿಯ ನಾಗರಿಕರ ಸಹಾಯವಾಣಿ",
    seniorDesc: "ಹಿರಿಯ ನಾಗರಿಕರ ಸಹಾಯ ಮತ್ತು ನೆರವಿಗಾಗಿ ರಾಷ್ಟ್ರೀಯ ಸಹಾಯವಾಣಿ.",
    disclaimer: "ಇವು ಸಾಮಾನ್ಯ ರಾಷ್ಟ್ರೀಯ ಸಹಾಯವಾಣಿ ಸಂಖ್ಯೆಗಳು. ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ, ಯಾವಾಗಲೂ ಸ್ಥಳೀಯ ಪೊಲೀಸರನ್ನು ಅಥವಾ ಹತ್ತಿರದ ತುರ್ತು ಸೇವೆಯನ್ನು ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ.",
  },
};

export function getEmergencyContent(uiLanguage) {
  return EMERGENCY_CONTENT[uiLanguage] || EMERGENCY_CONTENT.en;
}
